/* LYRICS DATA — Breaking My Heart, Lana Del Rey */
window.LYRICS2 = [
  { time: "00:12.40", text: "I wanna be the object of your affection" },
  { time: "00:15.74", text: "Give me all your time, touch, money and attention" },
  { time: "00:18.84", text: "Pick me up after school" },
  { time: "00:20.42", text: "You can be my baby" },
  { time: "00:21.98", text: "Maybe we could go somewhere" },
  { time: "00:23.52", text: "Get a little crazy" },
  { time: "00:24.88", text: "He's rich and I'm wishin' um, he could be more" },
  { time: "00:27.38", text: "Mr. Yum" },
  { time: "00:28.00", text: "Delicious to the maximum" },
  { time: "00:29.74", text: "Chew him up like bubble gum" },
  { time: "00:31.32", text: "I'm his pretty party favor" },
  { time: "00:34.38", text: "He says I'm his favorite flavor" },
  { time: "00:37.26", text: "Uh. Uh" },
  { time: "00:38.74", text: "Catch me ridin' like a bitch" },
  { time: "00:40.28", text: "Got the six forty five" },
  { time: "00:41.84", text: "Catch me ridin' with my bitch, uh" },
  { time: "00:44.16", text: "Blonde hair, Lana, that's my bitch, uh" },
  { time: "00:47.34", text: "You can tell by the swagger and the lips, uh" },
  { time: "00:50.49", text: "Uh. Uh" },
  { time: "00:51.20", text: "Catch me ridin' like a bitch" },
  { time: "00:52.76", text: "Got the six forty five" },
  { time: "00:54.28", text: "Catch me ridin' with my bitch, uh" },
  { time: "00:56.70", text: "Blonde hair, Lana, that's my bitch, uh" },
  { time: "00:59.83", text: "You can tell by the swagger and the lips, uh" },
  { time: "01:02.26", text: "You say that I am flawless, true perfection" },
  { time: "01:05.42", text: "So give me all your drugs, props, money and connections" },
  { time: "01:08.50", text: "Pick me up after school, acting kinda shady" },
  { time: "01:11.80", text: "You the coolest kid in town" },
  { time: "01:13.42", text: "I'm your little lady" },
  { time: "01:14.74", text: "He's tickin' em, kissin' em" },
  { time: "01:16.48", text: "Magical musician, um" },
  { time: "01:18.00", text: "Drivin' at the cinema" },
  { time: "01:19.62", text: "Lovin' on and lickin' em" },
  { time: "01:21.12", text: "He's my lovely lifesaver" },
  { time: "01:24.22", text: "Does it on my bad behavior" },
  { time: "01:27.14", text: "Uh. Uh" },
  { time: "01:28.60", text: "Catch me ridin' like a bitch" },
  { time: "01:30.16", text: "Got the six forty five" },
  { time: "01:31.70", text: "Catch me ridin' with my bitch, uh" },
  { time: "01:34.04", text: "Blonde hair, Lana, that's my bitch, uh" },
  { time: "01:37.20", text: "You can tell by the swagger and the lips, uh" },
  { time: "01:40.47", text: "Uh. Uh" },
  { time: "01:41.06", text: "Catch me ridin' like a bitch" },
  { time: "01:42.62", text: "Got the six forty five" },
  { time: "01:44.20", text: "Catch me ridin' with my bitch, uh" },
  { time: "01:46.58", text: "Blonde hair, Lana, that's my bitch, uh" },
  { time: "01:49.66", text: "You can tell by the swagger and the lips, uh" },
  { time: "01:52.30", text: "Swervin'. Swervin'" },
  { time: "01:53.96", text: "Gettin' all them dimes" },
  { time: "01:55.48", text: "Tell her I be doin', I be swaggin' to my prime" },
  { time: "01:58.62", text: "This ain't all the time. It happen all the time" },
  { time: "02:01.32", text: "That's a big contradiction, get yo money on your mind" },
  { time: "02:04.42", text: "Woah. Woah" },
  { time: "02:06.00", text: "Tell her I be on the chase" },
  { time: "02:07.92", text: "Chasin' for that paper, yeah, you see me on that race" },
  { time: "02:10.72", text: "Woah. Woah" },
  { time: "02:12.24", text: "Tell her I be going first" },
  { time: "02:14.28", text: "I be going first til they put me in a hearse" },
  { time: "02:16.92", text: "Say one big room full of bad bitches" },
  { time: "02:20.06", text: "No, one big room and it's full of mad bitches" },
  { time: "02:23.56", text: "Lana. Lana" },
  { time: "02:25.08", text: "Tell 'em what it is" },
  { time: "02:26.70", text: "Tell 'em that you do it and you, and you do it big" },
  { time: "02:29.44", text: "I said one big room full of bad bitches" },
  { time: "02:32.48", text: "No, it's one big room and it's full of mad bitches" },
  { time: "02:35.64", text: "I said Lana. Lana" },
  { time: "02:37.56", text: "Tell 'em what it is" },
  { time: "02:39.12", text: "Tell 'em when you do it that you only do it big" },
  { time: "02:41.96", text: "Uh. Uh" },
  { time: "02:43.42", text: "Catch me ridin' like a bitch" },
  { time: "02:44.96", text: "Got the six forty five" },
  { time: "02:46.52", text: "Catch me ridin' with my bitch, uh" },
  { time: "02:48.84", text: "Blonde hair, Lana, that's my bitch, uh" },
  { time: "02:52.02", text: "You can tell by the swagger and the lips, uh" },
  { time: "02:55.22", text: "Uh. Uh" },
  { time: "02:55.86", text: "Catch me ridin' like a bitch" },
  { time: "02:57.42", text: "Got the six forty five" },
  { time: "02:59.00", text: "Catch me ridin' with my bitch, uh" },
  { time: "03:01.42", text: "Blonde hair, Lana, that's my bitch, uh" },
  { time: "03:04.46", text: "You can tell by the swagger and the lips, uh" }
];
