/* LYRICS DATA — Ridin', A$AP Rocky ft. Lana Del Rey */
window.LYRICS3 = [
  { time: 0,   text: "I want to be your object," },
  { time: 3,   text: "of your affection" },
  { time: 5,   text: "Give me all your time," },
  { time: 6,   text: "touch, money, and attention" },
  { time: 8,   text: "Pick me up after school," },
  { time: 9,   text: "you can be my baby" },
  { time: 11,  text: "Maybe we could go somewhere," },
  { time: 12,  text: "get a little crazy" },
  { time: 14,  text: "He's rich and I'm wishin'," },
  { time: 15,  text: "um, he could be my Mister Yum" },
  { time: 17,  text: "Delicious to the maximum," },
  { time: 18,  text: "chew him up like bubble gum" },
  { time: 20,  text: "I'm his pretty party favor, he" },
  { time: 22,  text: "says I'm his favorite flavor" },

  { time: 24,  text: "" },

  { time: 26,  text: "Uh, uh, catch me ridin' like a bitch" },
  { time: 29,  text: "Got the six forty-five, catch" },
  { time: 30,  text: "me ridin' with my bitch" },
  { time: 32,  text: "Uh, long hair, Lana, that's my bitch" },
  { time: 35,  text: "Uh, You can tell by the" },
  { time: 36,  text: "swagger and the lips, uh" },
  { time: 38,  text: "Uh, uh, catch me ridin' like a bitch" },
  { time: 41,  text: "Got the six forty-five, catch" },
  { time: 42,  text: "me ridin' with my bitch" },
  { time: 44,  text: "Uh, long hair, Lana, that's my bitch" },
  { time: 47,  text: "Uh, You can tell by the" },
  { time: 48,  text: "swagger and the lips, uh" },

  { time: 50,  text: "" },

  { time: 52,  text: "You say that I am" },
  { time: 53,  text: "flawless, true perfection" },
  { time: 55,  text: "So give me all your drugs," },
  { time: 56,  text: "props, money, and connections" },
  { time: 58,  text: "Pick me up after school," },
  { time: 59,  text: "actin' kinda shady" },
  { time: 60,  text: "You're the coolest kid in" },
  { time: 62,  text: "town, I'm your little lady" },
  { time: 64,  text: "You're sick and I'm kissin'" },
  { time: 65,  text: "him, magical musician, how I'm" },
  { time: 67,  text: "Drivin' at the cinema," },
  { time: 68,  text: "lovin' him and lickin' him" },
  { time: 70,  text: "He's my lovely life saver" },
  { time: 72,  text: "Doesn't mind my bad behavior" },

  { time: 73,  text: "" },

  { time: 75,  text: "Uh, uh, catch me ridin' like a bitch" },
  { time: 79,  text: "Got the six forty-five, catch" },
  { time: 80,  text: "me ridin' with my bitch" },
  { time: 82,  text: "Uh, long hair, Lana, that's my bitch" },
  { time: 84,  text: "Uh, You can tell by the" },
  { time: 85,  text: "swagger and the lips, uh" },
  { time: 88,  text: "Uh, uh, catch me ridin' like a bitch" },
  { time: 91,  text: "Got the six forty-five, catch" },
  { time: 92,  text: "me ridin' with my bitch" },
  { time: 94,  text: "Uh, long hair, Lana, that's my bitch" },
  { time: 96,  text: "Uh, You can tell by the" },
  { time: 97,  text: "swagger and the lips, uh" },

  { time: 98,  text: "" },

  { time: 100, text: "Swervin', swervin'," },
  { time: 102, text: "gettin' all them dimes" },
  { time: 103, text: "Tell her I be doin', I" },
  { time: 104, text: "be swaggin' to my prime" },
  { time: 106, text: "This ain't all the time," },
  { time: 107, text: "it happens all the time" },
  { time: 109, text: "That's a big contradiction," },
  { time: 110, text: "get your money on your mind" },
  { time: 112, text: "What, what, tell her I be on a chase" },
  { time: 114, text: "Chasin' for that paper and" },
  { time: 116, text: "you see me on that race" },
  { time: 117, text: "What, what, tell her I be goin' first" },
  { time: 120, text: "I be gon' first and they" },
  { time: 122, text: "put me in a hearse, oh" },
  { time: 124, text: "One big room, full of bad bitches, no" },
  { time: 126, text: "One big room and it's" },
  { time: 127, text: "full of mad bitches" },
  { time: 129, text: "Lana, Lana, tell them what it is" },
  { time: 132, text: "Tell 'em that you doin'" },
  { time: 133, text: "it, you mean to do it big" },
  { time: 135, text: "I said, one big room, full" },
  { time: 137, text: "of bad bitches, no it's" },
  { time: 138, text: "One big room and it's full" },
  { time: 139, text: "of mad bitches, I said" },
  { time: 142, text: "Lana, Lana, tell them what it is" },
  { time: 144, text: "Tell 'em when you do it" },
  { time: 145, text: "that you only do it big" },

  { time: 147, text: "" },

  { time: 150, text: "Uh, uh, catch me ridin' like a bitch" },
  { time: 153, text: "Got the six forty-five, catch" },
  { time: 154, text: "me ridin' with my bitch" },
  { time: 156, text: "Uh, long hair, Lana, that's my bitch" },
  { time: 159, text: "Uh, You can tell by the" },
  { time: 160, text: "swagger and the lips, uh" },
  { time: 162, text: "Uh, uh, catch me ridin' like a bitch" },
  { time: 165, text: "Got the six forty-five, catch" },
  { time: 166, text: "me ridin' with my bitch" },
  { time: 168, text: "Uh, long hair, Lana, that's my bitch" },
  { time: 171, text: "Uh, You can tell by the" },
  { time: 172, text: "swagger and the lips, uh" },

  { time: 9999, text: "" }
];
